# Generated by Django 4.2.4 on 2023-09-16 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='brand',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='basket_brand', to='sample.brand'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_brand', to='sample.brand'),
        ),
    ]
